name: (Action) docker build & push to ECR
description: "Action for docker build & push to ECR"

inputs:
  image_name:
    required: true
    description: 'application project name'
  tags:
    required: false
    description: 'docker image tags to use. Values are List/CSV. https://github.com/docker/build-push-action#inputs'
    default: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
  tags_flavor:
    required: false
    description: 'https://github.com/docker/metadata-action#flavor-input'
    default: |
      latest=auto
      prefix=
      suffix=
  dockerfile:
    description: 'path and name of the Dockerfile'
    required: false
    default: 'deploy/Dockerfile'
  docker_build_context:
    required: false
    description: 'Docker build context'
    default: .
  platforms:
    required: false
    description: 'The platforms to build the image for. e.g. linux_amd64'
    default: linux/amd64,linux/arm64
  push_to_registry:
    required: false
    description: 'Flag for enabling a push to registry. Useful for testing.'
    default: 'true'
  ecr_aws_region:
    required: false
    description: 'ECR AWS region'
    default: eu-west-2
  ecr_registry:
    required: false
    description: 'ECR AWS endpoint'
    default: 942095822719.dkr.ecr.eu-west-2.amazonaws.com
  ECR_AWS_ACCESS_KEY_ID:
    required: true
    description: 'ECR AWS Access Key Id, stored as a secret'
  ECR_AWS_SECRET_ACCESS_KEY:
    required: true
    description: 'ECR AWS Secret Access Key, stored as a secret'


runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: "${{ inputs.ecr_registry }}/${{ inputs.image_name }}"
        tags: ${{ inputs.tags }}
        flavor: ${{ inputs.tags_flavor }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.ECR_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.ECR_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.ecr_aws_region }}

    - name: Login to Amazon ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.ecr_registry }}

    - name: Build and push
      id: build_push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.docker_build_context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push_to_registry }}
        tags: ${{ steps.meta.outputs.tags }}
        file: ${{ inputs.dockerfile }}

    - name: Debug - metadata output
      run: |
        echo ${{ steps.meta.outputs.tags }}
      shell: bash

    - name: Debug - docker build output
      run: |
        echo ${{ steps.build_push.outputs.metadata }}
      shell: bash
