# This is a basic workflow to help you get started with Actions

name: Deployment
concurrency:
    group: TestDeployment
    cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-alpha:
    needs: [build]
    runs-on: ubuntu-latest
    environment: test-alpha
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-beta:
    needs: [build]
    runs-on: ubuntu-latest
    environment: test-beta
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  pre-prod:
    needs: [deploy-beta, deploy-alpha]
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-prod1:
    needs: [pre-prod]
    runs-on: ubuntu-latest
    environment: prod1
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  deploy-prod2:
    needs: [pre-prod]
    runs-on: ubuntu-latest
    environment: prod2
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


